name: linux-test

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: [self-hosted, linux]
    steps:
    - name: Build Docker
      run: |
        docker build --build-arg="PY_VERSION=3.10" --tag ablator-test .
    - name: Test with pytest
      run: |
        docker run -v /var/run/docker.sock:/var/run/docker.sock --cpuset-cpus="0-4" --pid host --gpus all ablator pytest . --runslow --docker-tag ablator-test